// <auto-generated />
using System;
using MMSvitloE.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MMSvitloE.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20221130082229_Followers")]
    partial class Followers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MMSvitloE.Db.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DateUtc");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("MMSvitloE.Db.Follower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool?>("CanJoinGroups")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("CanReadAllGroupMessages")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("FollowingSvitloBot")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBot")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LanguageCode")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartedFollowUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartedUnfollowUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("SupportsInlineQueries")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Followers");
                });
#pragma warning restore 612, 618
        }
    }
}
